### PR TITLE
run black on ephemetoot.py

### PR DESCRIPTION
**Pull request by MarkEEaton**
I ran `$ black ephemetoot.py` on the code

Some things that it is doing:
- removing trailing spaces
- preferring double quotes over single quotes
- using four spaces as indents
- breaking arguments out onto multiple lines if they are too long
- combining arguments onto one line if they'll fit
- probably some other stuff

Let me know if you think this is an improvement!

### CODE REVIEW

**Comment by MarkEEaton** [comment]
Oops, I added a commit to this pull request that I didn't intend to. Git is hard :( 
Let me try to sort that out.

**Comment by MarkEEaton** [comment]
Ok, git problem solved. This pull request is back to how it was intended.

The commit I removed was one that allows for a test run of ephemetoot (in other words, where no toots are deleted). But that's possibly a future PR.

**Comment by hughrun** [comment]
Looks good! I wasn't sure about the 4-space indent, but now I've read the PEP8 explanation I'm on board.

A test run mode is a really good idea.

**Comment by MarkEEaton** [comment]
If you want to see what I was working on, [this branch is a draft](https://github.com/MarkEEaton/ephemetoot/blob/test-run/ephemetoot.py) of some test-run code. It supports some command line flags:

`$ python ephemetoot.py --test`
`$ python ephemetoot.py --help`

I'm not sure how I feel about it yet. I'd welcome your suggestions!

**Pull request merged**
