### PR TITLE
Add support for archiving toots into JSON files

### PR DESCRIPTION
**Pull request by jpmens**
Thank you for a very useful utility. I've found it practical in the past to archive a local copy of what I'm about to delete if only to refresh my memory at a later point in time. :-)

This small patch adds such a feature. If an `archive` is configured, it should be a writeable directory into which _ephemetoot_ will dump indented JSON into files named by the Toot's `id` (as this is something we can consider unique).

### CODE REVIEW

**Comment by hughrun** [comment]
Thanks for this @jpmens - seems like a useful addition and I like that it's a specified directory per account.

It looks like this will create an archive of every toot if there is an `archive` value in the config file? If a user wants a JSON archive of all toots, [that already is possible from the user settings](https://github.com/tootsuite/mastodon/pull/6460) so it seems a little overkill to do it every time they run `ephemetoot`. On the other hand I can definitely see value in archiving _toots we are about to delete_. 

So it would be good to get your opinion on some possible amendments:

1. trigger the archiving function at lines 144 & 174 so only deleted toots are archived rather than everything on the account
2. add an `--archive` flag so we only archive when there is an archive directory in the config **and** the `--archive` flag is used.

**Comment by jpmens** [comment]
It was, indeed, my intention that a full archive of everythying _ephemetoot_ "sees" is made. I'm aware of the optional toot archive which can be requested, but that's a manual interaction in the UI, something I don't mind avoiding. If we run _ephemetoot_ periodically, the way I've implemented the patch we get an automatic archive so to speak; it doesn't cost extra either, because we have the toots. :-)

I think that explains why I haven't done it as you suggest in point 1. above; I personally like the archive.

As to `--archive`, certainly that would be possible: my intention was that the archive directory in the config means a users *wants* the archive without requiring an additional option.

**Comment by jpmens** [comment]
I apologize: the `print(toot)` is not supposed to be there! I'm pushing a fix right now, and in fact it would already be there were it not for Github reporting

```
remote: Internal Server Error
```

during the `git push`; give me a few moments, please.

**Comment by jpmens** [comment]
I'm not sure what to do now. I pushed [this commit](https://github.com/jpmens/ephemetoot/commit/237e9fc67cae483cc1388f2911099aecd0512a0e) to my fork, but it's not yet appeared here. I'm assuming this has something to do with [Github's current status](https://www.githubstatus.com) which looks pretty red (and I feel sorry for them).

**Comment by jpmens** [comment]
OK, @hughrun, I think this is it now. Thank you for your patience.

**Pull request merged**
