### PR TITLE
add archive_media configuration option

### LINKED ISSUE #72: Optionally include media attachments in archives
**Does your proposal relate to...**

- [ ] documentation
- [ ] what is displayed when running ephemetoot
- [X] a new config value
- [ ] a new flag (option)
- [ ] something else

**Is your feature request related to a problem? Please describe.**
The archive option stores the json representation of a toot on disk.
The media_attachments array contains a list of URIs that point to fediverse server.
Once a toot is deleted media_attachments are deleted as well and are then lost.

**Describe the solution you'd like**
I would like to fetch the media attachments and store them alongside the json of the toot.
It is probably best to replicate the directory structure the servers uses, for example I see
`https://SERVER/media_attachments/files/000/718/385/original/IMAGE.png`
The file `IMAGE.png` should be stored in the directory `media_attachments/files/000/718/385/original` below the archive path.
This would be configurable by a new archive_media [yes/no] option.

**Would like to write the code yourself?**

- [X] I would like to write the code myself and then log a pull request
- [ ] I would like someone else to write the code
- [ ] I would like someone to help me write the code

### PR DESCRIPTION
**Pull request by fobser**
## Styles and docs

- [x] I have read the [contributing guide](https://github.com/hughrun/ephemetoot/blob/master/docs/contributing.md)
- [x] I have run `black` on my code
- [ ] My tests are listed in alphabetical order

## Tests

- [ ] I have added tests for this code in `tests/test_ephemetoot.py`
- [ ] I would like assistance to write the required tests
- [x] I don't know how to write test and would like someone to write them for me

The requests library doesn't support file:// URLs so I have no idea how to write a test for this.
It seems inappropriate to to fetch a random URL from the internet in a test.

# What this PR does

Changes in this pull request
With the archive_media option set to true, media attachments are
archived together with the toot.

# Related issues

Resolves #72

### CODE REVIEW

**Review by hughrun — CHANGES_REQUESTED** [review]
Hi @fobser 

Thanks so much for this PR! It appears to work as advertised.

I can add a test after I pull your final PR, which will help protect against regressions in future.

I have 2 requested changes

1.  Can you please add an `archive_media` value in `example-config.yaml`?
2. Some users will be using `ephemetoot` with multiple accounts. The media files should therefore ideally be saved to a filepath reflecting their original domain name. Can we update line 335 in `ephemetoot.py` to read:

```
media_archive_path = os.path.join(archive_path, url.netloc, dir_name[1:])
```

This should then save all images to `archive_path/server-domain.tld/filepath/filename.extension`, avoiding any (admittedly unlikely) filepath name collisions from different accounts.

**Comment by fobser** [comment]
Hi @hughrun 
I made the requested changes and force pushed my branch.

Thanks for handling the test, much appreciated. I had
a look at the existing tests but kinda got lost.

**Review by hughrun — APPROVED** [review]
Looks good! Thanks so much, will add tests and issue a new release soon.

If you'd like to be @mentioned by the ephemetoot account when I announce the new release, let me know your mastodon handle.

**Comment by fobser** [comment]
Thanks, I'm @florian@bsd.network

**Pull request merged**
